In [15]:
import pandas as pd
import numpy as np

# q1 - pandas version
pd.__version__

'2.3.1'

In [16]:
# q2 number of records in dataset
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
len(df)

9704

In [3]:
# dataset structure
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [11]:
# Q3 - checking which fuel_types are there
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [17]:
# Q3 - other way - show the number of unique values in each column
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [18]:
# Q4 - how many columns have missing values
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [19]:
# Q4 - how many columns have missing values - other command
df.isna().any().sum()

np.int64(4)

In [22]:
# recall data strucutre
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [28]:
# Q5 - maximum fuel efficiency
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [31]:
# Q6.1 - median value of horsepower
df.horsepower.median()

np.float64(149.0)

In [33]:
# Q6.2 - most frequent value of horsepower
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [36]:
# Q6.3 - filling the nan fields of horsepower column
df.horsepower = df.horsepower.fillna(df.horsepower.mode()[0])
# verification
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [37]:
# 6.4 calculate the median value one more time
df.horsepower.median()

np.float64(152.0)

In [67]:
# Q.7 - sum of weights
# 7.1 - all cars from asia
df[df['origin'] == 'Asia']
# 7.2 - only columns `vehicle_weight` and `model_year` 
df[df['origin'] == 'Asia'][['vehicle_weight','model_year']]
# 7.3 - only columns `vehicle_weight` and `model_year` - first 7 rows
df[df['origin'] == 'Asia'][['vehicle_weight','model_year']].head(7)
# 7.4 placing the result into array called X
X = df[df['origin'] == 'Asia'][['vehicle_weight','model_year']].head(7)
# 7.5 Compute matrix-matrix multiply between transpose of X (call it XTX) and X
# XT - transposed X
XT = X.T
# multiply XT and X into XTX
XTX = XT.dot(X)

In [68]:
X

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [69]:
XT

8            12           14           20  \
vehicle_weight  2714.21931  2783.868974  3582.687368  2231.808142   
model_year      2016.00000  2010.000000  2007.000000  2011.000000   

                         21           34           38  
vehicle_weight  2659.431451  2844.227534  3761.994038  
model_year      2016.000000  2014.000000  2019.000000

In [71]:
XTX

vehicle_weight    model_year
vehicle_weight    6.224833e+07  4.143122e+07
model_year        4.143122e+07  2.837334e+07

In [72]:
#7.6 - Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [73]:
# verification if we are still doing correct actions:
I = XTX_inv.dot(XTX)
I

array([[ 1.00000000e+00,  2.13808046e-15],
       [-3.87615815e-15,  1.00000000e+00]])

In [54]:
# 7.7. create array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [74]:
# 7.8 - multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = (XTX_inv.dot(XT)).dot(y))
w

array([0.01386421, 0.5049067 ])

In [75]:
# 7.9 - sum all the elements of w
w.sum()
 result

np.float64(0.5187709081074016)