In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [3]:
pd.__version__

'2.3.1'

In [8]:
a = np.zeros(5)

In [9]:
a

array([0., 0., 0., 0., 0.])

In [10]:
a[:]

array([0., 0., 0., 0., 0.])

In [11]:
n = np.array([ [1,2,3], [4,5,6], [7,8,9] ])

In [12]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
n[:,2]

array([3, 6, 9])

In [14]:
n[0,1] = 20
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
np.random.rand(5, 2)





array([[0.50524609, 0.0652865 ],
       [0.42812233, 0.09653092],
       [0.12715997, 0.59674531],
       [0.226012  , 0.10694568],
       [0.22030621, 0.34982629]])

In [16]:
np.random.rand(5, 2)

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

In [18]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [19]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])