In [4]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [23]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv')
len(df)


1462

In [24]:
# eda
df.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [25]:
df.dtypes[df.dtypes == 'object'].index

Index(['lead_source', 'industry', 'employment_status', 'location'], dtype='object')

In [26]:
for col in df.columns:
    print(col)
    print(df[col].head())
    print(df[col].unique())
    print(df[col].unique()[:5])
    print(df[col].nunique())
    print()
    

lead_source
0        paid_ads
1    social_media
2          events
3        paid_ads
4        referral
Name: lead_source, dtype: object
['paid_ads' 'social_media' 'events' 'referral' 'organic_search' nan]
['paid_ads' 'social_media' 'events' 'referral' 'organic_search']
5

industry
0           NaN
1        retail
2    healthcare
3        retail
4     education
Name: industry, dtype: object
[nan 'retail' 'healthcare' 'education' 'manufacturing' 'technology'
 'other' 'finance']
[nan 'retail' 'healthcare' 'education' 'manufacturing']
7

number_of_courses_viewed
0    1
1    1
2    5
3    2
4    3
Name: number_of_courses_viewed, dtype: int64
[1 5 2 3 0 4 6 8 7 9]
[1 5 2 3 0]
10

annual_income
0    79450.0
1    46992.0
2    78796.0
3    83843.0
4    85012.0
Name: annual_income, dtype: float64
[79450. 46992. 78796. ... 45688. 71016. 92855.]
[79450. 46992. 78796. 83843. 85012.]
1267

employment_status
0       unemployed
1         employed
2       unemployed
3              NaN
4    self_employed


In [27]:
categorical_columns = list(df.dtypes[df.dtypes =='object'].index)

In [28]:
categorical_columns

['lead_source', 'industry', 'employment_status', 'location']

In [29]:
# DATA PREPARATION
# We have annual_income of type float with nulls, replacing them with 0.0
df.isnull().sum()
#df = df['annual_income'].fillna(0.0)

#df.isnull().sum()

lead_source                 128
industry                    134
number_of_courses_viewed      0
annual_income               181
employment_status           100
location                     63
interaction_count             0
lead_score                    0
converted                     0
dtype: int64

In [40]:
df_prepared = df
df_prepared.annual_income = df_prepared.annual_income.fillna(0.0)

categorical_columns = list(df_prepared.dtypes[df_prepared.dtypes == 'object'].index)

for c in categorical_columns:
    df_prepared[c] = df_prepared[c].fillna('NA')

#df_prepared


In [41]:
df_prepared.isnull().sum()

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [43]:
# Q1 - Most frequesnt observstion in column industry. Answer - retail
df_prepared.industry.mode()

0    retail
Name: industry, dtype: object

In [48]:
# Q2 - correlation matrix - Answer: `
annual_income and interaction_count`
numerical1 = ['interaction_count', 'number_of_courses_viewed' ]
numerical1

['interaction_count', 'number_of_courses_viewed']

In [49]:
df_prepared[numerical1].corrwith(df_prepared.lead_score)

interaction_count           0.009888
number_of_courses_viewed   -0.004879
dtype: float64

In [51]:
numerical2 = ['number_of_courses_viewed', 'annual_income' ]
numerical2

['number_of_courses_viewed', 'annual_income']

In [52]:
df_prepared[numerical2].corrwith(df_prepared.interaction_count)

number_of_courses_viewed   -0.023565
annual_income               0.027036
dtype: float64

In [57]:
# num_from = ['interaction_count', 'number_of_courses_viewed', 'number_of_courses_viewed', 'annual_income' ]
# num_to = ['lead_score', 'lead_score', 'interaction_count', 'interaction_count' ]

# for c in num_from:
#   result = df_prepared[c].corrwith(df_prepared[num_to])
#   result

AttributeError: 'Series' object has no attribute 'corrwith'